language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: "./travis_build.sh"
env:
  global:
    secure: s6Ym9f5CbhQuHzNOPcfJ3Kooe5RPHwu+rA526bIJOFZUeBFqXKNfEPsnV/XTk/WngJ4waDOkJh+eCjXVpNK1hRIDudzCKRiWXMJRAvKb3e2d/bg65tOTYwdgLiRsBy+4sxvDKrEXm/zDe4slFMjyFVr1arC8ZbVSka3qoEdTj6k45Gw3LRaUv/P4rHTb2eAbDHE6Dkm4SyXirmBUS83Rpf3ahR06RRh0oFB9j/QC3FDJoBJ0Uhi8qHLSQiyJKaFq+eiT12viwHUpmYIiCHPMGTP9kp6XLe7lm6c2ZR+B6JKGPEfbiF6R/gOPWGibzsxR1w7OTgIHSiuqSoShZuzAeXkO20Xuy/HfxXhGfsa2lLDQ9ZaMBg5rqggXr23PNsVH4s6SD/Yw3tu9g/M97ux2spdMAQq5Z4nry9XjlU8FuDzI51DbPUmiJJ5gwD3QbRxecayHyG5wztBuUkNFyXbHOiscQ/oYquqtolCLdYqhJjz4vlA1WLah8WDFBe4H8VsVcNPvdLgcaW902MYVOKuLfIB1pVEOLBrW1NLaWw0KskWDRzGAWIE895eoY9LcHeaqr54rHzH59mrtXXqB5+rlEbkwqUKgZa2cvJIU1H5PAtrf/26AC8Ms3yBzmtCVPmvNYdbRjfiS01M+b+CvbpfU5Tjv32u/kzy/q/Ctne2t0So=
deploy:
  provider: releases
  api_key:
    secure: WrsEpopbWaZhLeKyIb7lr+TotrLMumhy38n1Ybk7O5bFI2zpbZoMY5YTB/RvHx6pxoG4OeF7+vPRb6PKCEpGMcRKzgWR8bgYYuYF5/7RIPOPc0uvH81iggXhfOpo0eDh+1MT4hv3bG0I9JuMEQXZiVtkbfBU9l6bXTsOIwwqHcugqG4+bw0hfvlxdQebDlrzt26fumHBwC63OGOZ1bxfLwXiVACX8s8tmMebw/QFoq0jcxpt5z5ZVjQtBty5C/CWYS7aMl+zcCSUheKhG6YoylhY3pzSwhc0fG8LJQFm4UnjzUZH+Y6fxdPzQj+GEVCpBsonjkaSyOTx3BCeRx1YfvqpVHnoZI7g7Y3inSMJSYp8Xeq5FIUu+8UQqiomwOAPUp1rbCuEIkSuEiez+yohPIcbLZ/fwotiSJfmoSKRo66XNFI3Rmo79x3dXFI+mQOQJdweeJcw4FyXpNc0o80Vnfm8XByAALPwxL2eKaQbv88dGX0TJkrwPM6XvOA8Psb/E65UmD4vcAsKTu1VTqP2MDkP+5UTQoyc55ItlFCWKh1Dvs5vc46ewXpzyTDxPYOUnPhTnzS+QQ8cDBb1PY5njzqNwcBUN0lz2S9BnXsfXehWGi3JmxI3Ia+TmBYCNIoREeszYsXzATXL4LtidAWqpfVkoyggHjvz57Ygj/plYU0=
  file: bl.s
  on:
    repo: manz/bahamut_lagoon
