language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: ./travis_build.sh
env:
  global:
    secure: s6Ym9f5CbhQuHzNOPcfJ3Kooe5RPHwu+rA526bIJOFZUeBFqXKNfEPsnV/XTk/WngJ4waDOkJh+eCjXVpNK1hRIDudzCKRiWXMJRAvKb3e2d/bg65tOTYwdgLiRsBy+4sxvDKrEXm/zDe4slFMjyFVr1arC8ZbVSka3qoEdTj6k45Gw3LRaUv/P4rHTb2eAbDHE6Dkm4SyXirmBUS83Rpf3ahR06RRh0oFB9j/QC3FDJoBJ0Uhi8qHLSQiyJKaFq+eiT12viwHUpmYIiCHPMGTP9kp6XLe7lm6c2ZR+B6JKGPEfbiF6R/gOPWGibzsxR1w7OTgIHSiuqSoShZuzAeXkO20Xuy/HfxXhGfsa2lLDQ9ZaMBg5rqggXr23PNsVH4s6SD/Yw3tu9g/M97ux2spdMAQq5Z4nry9XjlU8FuDzI51DbPUmiJJ5gwD3QbRxecayHyG5wztBuUkNFyXbHOiscQ/oYquqtolCLdYqhJjz4vlA1WLah8WDFBe4H8VsVcNPvdLgcaW902MYVOKuLfIB1pVEOLBrW1NLaWw0KskWDRzGAWIE895eoY9LcHeaqr54rHzH59mrtXXqB5+rlEbkwqUKgZa2cvJIU1H5PAtrf/26AC8Ms3yBzmtCVPmvNYdbRjfiS01M+b+CvbpfU5Tjv32u/kzy/q/Ctne2t0So=
