entrypoint = "bl.s"
module-paths = ["build/obj", "src", "build/gen"]
include-paths = ["src", "."]
board = "SHVC-1J3M-20"  # HiROM + 8 KB battery SRAM
rom_size = 0x400000     # 3 MB image expanded to 4 MB (banks F0-FF)
