[project]
name = "bahamut_lagoon"
version = "0.0.0.dev0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["a816==1.1.0a40", "pillow", "numpy"]

[project.urls]
Homepage = "https://github.com/manz/bahamut_lagoon"

[dependency-groups]
dev = ["pytest", "ruff"]

[tool.uv]
package = false

[tool.ruff]
line-length = 120
