[project]
name = "bahamut_lagoon"
version = "0.0.0.dev0"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "a816==1.1.0rc3",
    "pillow",
    "numpy",
    "katsuji==0.2.2",
]

[project.urls]
Homepage = "https://github.com/manz/bahamut_lagoon"

[dependency-groups]
dev = ["kintsuki[visual]==0.0.0a18", "pytest", "ruff==0.17.0"]

[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = ["utils", "tests"]
pythonpath = ["."]

[tool.ruff]
line-length = 120
