[project]
name = "bahamut_lagoon"
version = "0.0.0.dev0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a816==1.1.0a51",
    "pillow",
    "numpy",
    "katsuji==0.1.1",
]

[project.urls]
Homepage = "https://github.com/manz/bahamut_lagoon"

[dependency-groups]
dev = ["kintsuki[visual]==0.0.0a17", "pytest", "ruff==0.16.10"]

[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = ["utils", "tests"]
pythonpath = ["."]

[tool.ruff]
line-length = 120
