"""
The 8-byte name tables (characters, classes, dragons, enemies) and the full names small_vwf draws instead.

Every engine indexes these tables as base + id * 8, so the records keep their size and hold the name cut to eight
codes. The full names go in a generated a816 module: small_vwf_render, handed a record's address, reads the full
name in its place.
"""

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

from script import Table

from utils.cartridge import rom_offset

RECORD = 8
END = 0xFF
PAD = 0xFE


@dataclass(frozen=True)
class NameTable:
    label: str
    source: Path
    address: int  # bus address of record 0's name
    record: int = RECORD  # bytes from one record to the next


NAME_TABLES = (
    NameTable("char_names", Path("text/fr/names.xml"), 0xEF0380),
    NameTable("enemy_names", Path("text/enemies.xml"), 0xEF1F50),
    NameTable("class_names", Path("text/classes.xml"), 0xEF6360),
    NameTable("dragon_names", Path("text/dragons.xml"), 0xEF63D8),
    NameTable("spell_names", Path("text/spells.xml"), 0xEF5920),
)
ITEM_NAMES = Path("text/items.xml")
ITEM_RECORDS = 0xEF3CA0  # icon, then the name cut to a record
ITEM_TABLE = NameTable("item_names", ITEM_NAMES, ITEM_RECORDS + 1, 1 + RECORD)  # the names, past each icon


def read_names(source: Path) -> list[str]:
    return [(string.text or "").removesuffix("[0xff]") for string in ET.parse(source).getroot()]


SMALL_FONT_FOLD = str.maketrans("ÀÂÇÈÉÊËÎÏÔÙÛ", "AACEEEEIIOUU")  # small_font has no accented capitals


def encode(table: Table, name: str) -> bytes:
    """A name in the 8x8 text codes, accented capitals folded to the letters small_font draws."""
    return table.to_bytes(name.translate(SMALL_FONT_FOLD).replace(" ", r"\s"))


def short_record(codes: bytes) -> bytes:
    """The name cut to a record: up to eight codes, FF-terminated when shorter, FE-padded."""
    record = codes[:RECORD]
    if len(record) < RECORD:
        record += bytes([END])
    return record.ljust(RECORD, bytes([PAD]))


def insert_short_names(writer, table: Table) -> None:
    for name_table in NAME_TABLES:
        records = b"".join(short_record(encode(table, name)) for name in read_names(name_table.source))
        writer.write_block(records, rom_offset(name_table.address))


def item_records(table: Table, source: Path = ITEM_NAMES) -> bytes:
    """Item name records: the icon code, then the name as short_record cuts it."""
    records = b""
    for string in ET.parse(source).getroot():
        records += bytes([int(string.get("icon"), 16)]) + short_record(encode(table, string.text or ""))
    return records


def insert_item_names(writer, table: Table) -> None:
    writer.write_block(item_records(table), rom_offset(ITEM_RECORDS))


def long_names_source(table: Table) -> str:
    """The a816 module of full names: a descriptor per table (record 0, count, pointers, record size), then the
    strings."""
    descriptors = []
    pointers = []
    strings = []
    for name_table in (*NAME_TABLES, ITEM_TABLE):
        names = read_names(name_table.source)
        descriptors += [
            f"    .dl 0x{name_table.address:06X}",
            f"    .dw {len(names)}",
            f"    .dw _{name_table.label}",
            f"    .db {name_table.record}",
        ]
        pointers.append(f"_{name_table.label}:")
        for index, name in enumerate(names):
            label = f"_{name_table.label}_{index}"
            pointers.append(f"    .dw {label}")
            codes = ", ".join(f"0x{code:02X}" for code in (*encode(table, name), END))
            strings += [f"{label}:", f"    .db {codes}"]
    return "\n".join(
        [
            '"""Full names small_vwf reads in place of the 8-byte records. Generated by build.py."""',
            "",
            '.include "src/expansion.i"',
            "",
            ".alloc long_names in expansion {",
            "long_name_tables:",
            *descriptors,
            "    .dl 0x000000",
            *pointers,
            *strings,
            "}",
            "",
        ]
    )
