name: CI

on:
  push:
    branches:
      - master
  create:
    tags:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Requirements
      if: steps.cache-requirements.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
    - name: Build patch
      run: ./build.sh
      env:
        BAHAMUT_PASSWORD: ${{ secrets.BAHAMUT_PASSWORD }}
    - name: Upload nightly patch artifact
      uses: actions/upload-artifact@v1
      with:
        name: bl-nightly
        path: bl.ips
